GECI-42 Actualiza reporte de cormorán
IslasGECI/cormorant_population_growth pull request #5
Opened 2021-03-11 16:57 UTC by islasfernando

2021-03-11 20:35 UTC, nepito requested changes
Listo @islasfernando aquí te dejó mis comentarios. También está [este otro _pr_](https://github.com/IslasGECI/cormorant_population_growth/pull/4/files), tal vez valga la pena incorporar alguna de las sugerencias. ¿Tú cómo la ves?

2021-03-11 20:35 UTC, nepito commented on reports/tendencia_poblacional_cormoran.tex
> +    \includegraphics[scale=0.7]{figures/cormorant_population_trend_san_roque.png}
Por favor actualiza el [pie de figura](https://github.com/IslasGECI/cormorant_population_growth/pull/5/files?file-filters%5B%5D=.csv&file-filters%5B%5D=.tex&file-filters%5B%5D=No+extension#diff-2dd3c3e159475e07908598be052bcdeccb2840c9a9daaf3c84bc329ce723d344R154) para Alcatraz, ahora tenemos 21 temporadas.

2021-03-11 20:35 UTC, nepito commented on reports/tendencia_poblacional_cormoran.tex
> +\caption{En negro se muestran los máximos en la cantidad de nidos activos de cormorán orejón para cada temporada del periodo 1969-2006 en Isla Coronado Sur. La banda azul representa el intervalo de c
Por favor actualiza el pie de figura, pues dice que no encontramos tendencias y según la tabla 2, están en crecimiento. Siguiendo lo que dice para asunción, tal vez debería de decir:
 ```suggestion
\caption{En negro se muestran los máximos en la cantidad de nidos activos de cormorán orejón para cada temporada del periodo 1969-2006 en Isla Coronado Sur. La banda azul representa el intervalo de confianza del 95\% para la tasa de crecimiento. La línea azul y el valor de $\lambda$ mostrado en la gráfica, representan el valor central de la distribución bootstrapping de la tasa de crecimiento. El valor p indica que el tamaño poblacional de la colonia está en crecimiento.}
```

2021-03-11 20:35 UTC, nepito commented on reports/tendencia_poblacional_cormoran.tex
> +\caption{En negro se muestran los máximos en la cantidad de nidos activos de cormorán orejón para cada temporada del periodo 1971-2006 en Isla Coronado Norte. La banda azul representa el intervalo de
Por favor actualiza el pie de figura, pues dice que no encontramos tendencias y según la tabla 2, están en crecimiento. Siguiendo lo que dice para asunción, tal vez debería de decir:
```suggestion
\caption{En negro se muestran los máximos en la cantidad de nidos activos de cormorán orejón para cada temporada del periodo 1971-2006 en Isla Coronado Norte. La banda azul representa el intervalo de confianza del 95\% para la tasa de crecimiento. La línea azul y el valor de $\lambda$ mostrado en la gráfica, representan el valor central de la distribución bootstrapping de la tasa de crecimiento. El valor p indica que el tamaño poblacional de la colonia está en crecimiento.}
```

2021-03-11 21:37 UTC, islasfernando commented
> Listo @islasfernando aquí te dejó mis comentarios. También está [este otro _pr_](https://github.com/IslasGECI/cormorant_population_growth/pull/4/files), tal vez valga la pena incorporar alguna de las sugerencias. ¿Tú cómo la ves?

@nepito para que este reporte sea entregado lo más pronto posible mejor en otra tarjeta.

Tengo pensado implementar algo así, pero en `analytictools` para que se pueda usar en todos los otros repos en los que hemos aplicado lambdas-bootstrap. :v:

2021-03-16 19:43 UTC, nepito requested changes
Segunda tanda

2021-03-16 19:43 UTC, nepito commented on src/calculate_cormorant_growth_rate
> +    plot_data = plot_data.dropna(subset=[interest_variable])
Creo que esta línea está repetida con la [línea 48](https://github.com/IslasGECI/cormorant_population_growth/pull/5/files?file-filters%5B%5D=.csv&file-filters%5B%5D=.sql&file-filters%5B%5D=No+extension#diff-ccf085bc4078d93393b27df2f8cf04e7b43471abf3393bbac9ab093bad27a31cR48). No sé si necesitamos las dos, si sí por favor refactoriza en una función para que quede claro qué hacemos. Si no ocupamos las dos por favor borra alguna de las dos.

2021-03-16 19:48 UTC, nepito commented on src/calculate_max_nest_quantity
> +  Temporada,
Para este ya me ayudó @MaritzaB

2021-03-16 20:48 UTC, nepito commented on src/calculate_cormorant_growth_rate
>      p = leg.get_window_extent()
Por favor utiliza un nombre más descriptivo. No sé qué sugerirte, la verdad.

2021-03-17 18:01 UTC, nepito approved these changes
Listo @islasfernando solo te dejé una duda. Me avisas, para cerrar el _pr_ y cambiar a 2000 los ciclos del _bootstrapping_.

2021-03-17 18:02 UTC, nepito commented on reports/tendencia_poblacional_cormoran.tex
> +\caption{En negro se muestran los máximos en la cantidad de nidos activos de cormorán orejón para cada temporada en el periodo de 2000-2020 en Isla Alcatraz. La banda azul representa el intervalo de
Muchas gracias por atender esta sugerencia :raised_hands:

2021-03-17 18:38 UTC, islasfernando commented on src/calculate_cormorant_growth_rate
> +    legend_box_positions = leg.get_window_extent()
Si es el mismo, le cambie de nombre y lo puse como entrada en `plot_growth_rate_interval`

 `plot_growth_rate_interval(legend_mpl_object, lambda_latex)`

2021-03-17 18:40 UTC, islasfernando commented
Listo @nepito, cambié el nombre del `leg` :v:

2021-03-18 22:39 UTC, merged